import { clusterCells, nearestCell } from './path.ts';
import type { TowerId } from './types.ts';
import { UPGRADES } from './upgrades.ts';

/**
 * Seven boards a player might actually build, written as spending plans.
 *
 * The question this project keeps asking is not "is the game winnable" but
 * "does more than one build win", and that cannot be answered by a single
 * board. Each entry here is one *shape* the tower set offers -- volume of
 * small hits, few big ones, splash at the corners, holding without killing,
 * a rate buff feeding two hot guns, and the ordinary mixture a new player
 * makes.
 *
 * A build is an *ordered* plan, not a finished board: the campaign harness
 * walks it front to back and buys the next entry when the purse allows, so
 * the order is the player's decision about what to own first. Repeating a
 * cell with a bigger suffix is how a plan says "come back and upgrade this".
 *
 * They are stored as loadout strings rather than as objects because the rule
 * in `loadout.ts` cuts both ways: if a build cannot be typed at the command
 * line, it cannot be reproduced by hand, and a measurement nobody can
 * reproduce is a rumour.
 *
 * ## What these boards learned from a real one
 *
 * Every board in this file used to be generated by spreading towers evenly
 * along the street and then improving whichever one was least improved. All
 * six lost, at every seed, while the game was being finished comfortably by
 * hand -- so the boards had stopped representing anybody, and the harness was
 * measuring its own generator rather than the game. A board played by hand and
 * recorded (`corner`, below) clears every seed with fourteen lives to spare.
 *
 * Two things separated it from the generated ones, and both are now the rule
 * here rather than the exception:
 *
 * **Concentrate.** Spreading by lane distance gives each tower one stretch of
 * road and no two towers the same crowd. The played board packed everything
 * into one knot beside the first hairpin -- thirteen towers inside a 240px box
 * that covers lane distances 160-400 *and* 840-960, because the street doubles
 * back through it. One Clara hurried six guns; one Barbara caught what all of
 * them were shooting at.
 *
 * **Finish a tower before starting the next.** Alternating upgrades across
 * every tower on the board is what a plan does when it has no opinion, and it
 * buys eight mediocre towers instead of four good ones.
 *
 * Coverage alone is not the trick, incidentally, and it was measured: putting
 * the old spread-out builds on the highest-coverage cells in the board, but
 * still scattered, still lost. The concentration is what pays.
 */

/** One tower in a build, and the capstone it ends on. */
interface Slot {
  def: TowerId;
  /**
   * The capstone this tower ends on, or none.
   *
   * On the slot rather than in a second list beside it. These used to be
   * paired by index and drifted: `control` asked a Knitting Norah for
   * Barbara's Big Batch and a Protest Pete for Walter's Stone Wall, eight
   * entries in all, and nothing caught it because the build was too poor to
   * ever reach them. A capstone that cannot be written apart from its tower
   * cannot come adrift from it.
   */
  capstone?: string;
}

interface BuildSpec {
  blurb: string;
  /**
   * Where along the street this board knots itself, as a lane distance.
   *
   * Builds anchor in different places so they remain different boards; what
   * distinguishes them beyond that is what they are made of.
   */
  anchor: number;
  slots: Slot[];
}

/** How wide a knot may be. Wide enough to matter, tight enough for a Clara. */
const KNOT = 150;

/**
 * Resolve a build's slots to real cells, then write it in loadout grammar.
 *
 * Ordinary towers are clustered around the anchor, best-seeing cell first.
 * A blockade cannot be: Walter stands *in* the road, so his cell is chosen the
 * only way it can be, by lane distance.
 */
function render(spec: BuildSpec): string {
  const taken: { col: number; row: number }[] = [];
  const cells = spec.slots.map((s) => {
    if (s.capstone && !UPGRADES[s.def].capstones.some((c) => c.id === s.capstone)) {
      throw new Error(
        `build slot ${s.def} asks for capstone "${s.capstone}", which belongs to ` +
          `another tower -- ${s.def} has ${UPGRADES[s.def].capstones.map((c) => c.id).join(' and ')}`,
      );
    }
    const cell =
      s.def === 'walter'
        ? nearestCell(spec.anchor, 'blocker', taken)
        : clusterCells(spec.anchor, 1, TOWERS_RANGE[s.def], KNOT, taken)[0]!;
    taken.push(cell);
    return cell;
  });

  // Put one down, then improve whichever standing tower is furthest behind,
  // and once the board is full keep improving. Capstones last, because they
  // are the most expensive thing a plan can want and the board has to exist
  // first.
  //
  // Taking each tower all the way before placing the next was tried and is
  // worse, which was worth learning: it spends 285 coins finishing one Norah
  // while the street is still being walked by everything else, and `control`
  // died on round three of it. Concentration pays on the ground; it does not
  // pay in the order money is spent.
  const out: string[] = [];
  const tiers = spec.slots.map(() => ({ a: 0, b: 0 }));
  const placed: number[] = [];
  const at = (i: number): string => `${spec.slots[i]!.def}@${cells[i]!.col},${cells[i]!.row}`;
  const bits = (i: number): string =>
    (tiers[i]!.a ? `a${tiers[i]!.a}` : '') + (tiers[i]!.b ? `b${tiers[i]!.b}` : '');

  const improve = (): boolean => {
    const order = [...placed].sort(
      (x, y) => tiers[x]!.a + tiers[x]!.b - (tiers[y]!.a + tiers[y]!.b) || x - y,
    );
    for (const i of order) {
      const t = tiers[i]!;
      if (t.a <= t.b && t.a < 2) t.a++;
      else if (t.b < 2) t.b++;
      else continue;
      out.push(`${at(i)}+${bits(i)}`);
      return true;
    }
    return false;
  };

  spec.slots.forEach((_, i) => {
    out.push(at(i));
    placed.push(i);
    improve();
  });
  while (improve());
  spec.slots.forEach((s, i) => {
    if (s.capstone) out.push(`${at(i)}+a2b2:${s.capstone}`);
  });
  return out.join(' ');
}

/**
 * The reach each tower is placed for.
 *
 * A cell is picked for how much road *this* tower could see from it, so a Bill
 * is placed where his 225px reach pays and a Norah where her 95 does. Read
 * from the base stats rather than the bought ones: a plan chooses a cell
 * before it can afford the upgrades.
 */
const TOWERS_RANGE: Record<TowerId, number> = {
  norah: 95,
  barbara: 105,
  pete: 88,
  bill: 225,
  walter: 0,
  clara: 90,
};

const s = (def: TowerId, capstone?: string): Slot => ({ def, capstone });

const SPECS: Record<string, BuildSpec> = {
  /** Knitters, and as little else as the shape allows. Volume of small hits. */
  swarm: {
    blurb: 'a knot of knitters, volume over size',
    anchor: 900,
    slots: [
      s('norah', 'longYarn'),
      s('norah', 'longYarn'),
      s('norah', 'tripleKnit'),
      s('norah', 'longYarn'),
      s('norah', 'tripleKnit'),
      s('norah', 'longYarn'),
      s('norah', 'tripleKnit'),
      s('norah', 'longYarn'),
      s('norah', 'tripleKnit'),
      s('norah', 'longYarn'),
      s('norah', 'tripleKnit'),
      s('norah', 'longYarn'),
    ],
  },

  /** Binoculars, where their reach covers the road going out and coming back. */
  sniper: {
    blurb: 'binoculars stacked where the street doubles back',
    anchor: 1180,
    slots: [
      s('bill', 'piercingShot'),
      s('bill', 'deadeye'),
      s('bill', 'piercingShot'),
      s('clara', 'doubleEspresso'),
      s('bill', 'deadeye'),
      s('bill', 'piercingShot'),
      s('norah', 'longYarn'),
      s('bill', 'deadeye'),
      s('bill', 'piercingShot'),
    ],
  },

  /** Cinnamon rolls where a crowd bunches up, and something to thin it. */
  area: {
    blurb: 'cinnamon rolls over a bend, where the crowd bunches',
    anchor: 620,
    slots: [
      s('norah', 'longYarn'),
      s('barbara', 'bigBatch'),
      s('barbara', 'freshBatch'),
      s('barbara', 'bigBatch'),
      s('barbara', 'freshBatch'),
      s('clara', 'doubleEspresso'),
      s('barbara', 'bigBatch'),
      s('barbara', 'freshBatch'),
      s('norah', 'longYarn'),
      s('barbara', 'bigBatch'),
    ],
  },

  /** Stun and a blockade, holding the road while a thin gun line works. */
  control: {
    blurb: 'megaphones and a garden wall, holding while a thin gun line works',
    anchor: 700,
    slots: [
      s('pete', 'megaphone'),
      s('barbara', 'bigBatch'),
      s('walter', 'stoneWall'),
      s('pete', 'bullhorn'),
      s('norah', 'longYarn'),
      s('barbara', 'freshBatch'),
      s('pete', 'megaphone'),
      s('clara', 'doubleEspresso'),
      s('norah', 'longYarn'),
      s('barbara', 'bigBatch'),
    ],
  },

  /** Coffee stacked on a small number of guns run very hot. */
  support: {
    blurb: 'three coffees, everything nearby firing far too fast',
    anchor: 1500,
    slots: [
      s('norah', 'longYarn'),
      s('clara', 'doubleEspresso'),
      s('bill', 'deadeye'),
      s('clara', 'secondRound'),
      s('norah', 'longYarn'),
      s('bill', 'piercingShot'),
      s('clara', 'doubleEspresso'),
      s('norah', 'longYarn'),
      s('bill', 'deadeye'),
      s('norah', 'longYarn'),
      s('bill', 'piercingShot'),
      s('clara', 'secondRound'),
      s('bill', 'deadeye'),
      s('norah', 'longYarn'),
    ],
  },

  /** One of most things: the board a first-time player ends up with. */
  mixed: {
    blurb: 'one of most things, the obvious first board',
    anchor: 340,
    slots: [
      s('norah', 'longYarn'),
      s('bill', 'piercingShot'),
      s('clara', 'secondRound'),
      s('barbara', 'bigBatch'),
      s('bill', 'deadeye'),
      s('norah', 'longYarn'),
      s('pete', 'bullhorn'),
      s('bill', 'piercingShot'),
      s('barbara', 'freshBatch'),
      s('norah', 'longYarn'),
      s('bill', 'deadeye'),
      s('clara', 'doubleEspresso'),
      s('barbara', 'bigBatch'),
    ],
  },
};

/**
 * A board played by hand and recorded, kept exactly as it was played.
 *
 * Written out rather than generated, because that is the point of it: it is
 * the only entry here that is evidence rather than a proposal, and rewriting
 * it into the vocabulary above would quietly turn it back into a proposal. It
 * was captured with the `L` key while playing at localhost:5173 -- see
 * CLAUDE.md -- on a run that was won.
 *
 * Keep it verbatim. If a change to the game stops this board clearing, that is
 * a finding worth having, and it is only worth having while the board is still
 * the one somebody actually won with.
 */
const PLAYED =
  'norah@3,4 norah@7,6 norah@7,6+b1 norah@7,6+a1b1 norah@7,6+a1b2 norah@3,4+a1 ' +
  'norah@7,6+a2b2 norah@3,4+a1b1 norah@3,4+a2b1 bill@9,5 bill@9,5+b1 norah@3,4+a2b2 ' +
  'norah@7,6+a2b2:longYarn norah@3,4+a2b2:longYarn clara@6,5 clara@6,5+b1 clara@6,5+b2 ' +
  'bill@9,5+b2 bill@9,5+a1b2 barbara@4,5 barbara@4,5+a1 barbara@4,5+a2 barbara@4,5+a2b1 ' +
  'barbara@4,5+a2b2 barbara@4,5+a2b2:bigBatch clara@6,5+a1b2 clara@6,5+a2b2 ' +
  'clara@6,5+a2b2:secondRound bill@9,5+a2b2 bill@9,5+a2b2:piercingShot bill@9,6 ' +
  'bill@9,6+a1 bill@9,6+a2 bill@9,6+a2b1 bill@9,6+a2b2 bill@9,6+a2b2:piercingShot ' +
  'norah@8,5 norah@8,5+b1 norah@8,5+b2 norah@8,5+a1b2 norah@8,5+a2b2 ' +
  'norah@8,5+a2b2:longYarn pete@4,4 pete@4,4+a1 pete@4,4+a2 pete@4,4+a2b1 pete@4,4+a2b2 ' +
  'bill@9,4 pete@4,4+a2b2:bullhorn bill@9,4+a1 bill@9,4+a2 bill@9,4+a2b1 bill@9,4+a2b2 ' +
  'bill@9,4+a2b2:piercingShot barbara@7,7 barbara@7,7+a1 barbara@7,7+a2 barbara@7,7+a2b1 ' +
  'barbara@7,7+a2b2 barbara@7,7+a2b2:bigBatch bill@9,3 bill@8,4 bill@7,5';

export interface Build {
  name: string;
  blurb: string;
  /** The plan, in the grammar `parseLoadout` reads. */
  loadout: string;
}

export const BUILDS: Build[] = [
  ...Object.entries(SPECS).map(([name, spec]) => ({
    name,
    blurb: spec.blurb,
    loadout: render(spec),
  })),
  { name: 'corner', blurb: 'played by hand at the first hairpin, and won', loadout: PLAYED },
];

export const BUILD_NAMES: string[] = BUILDS.map((b) => b.name);

export function buildNamed(name: string): Build {
  const found = BUILDS.find((b) => b.name === name);
  if (!found) throw new Error(`no build "${name}" -- known: ${BUILD_NAMES.join(', ')}`);
  return found;
}
