import { clusterCells, nearestCell } from './path.ts';
import type { CapstoneId, CapstoneIds, TowerId } from './types.ts';
import { UPGRADES } from './upgrades.ts';

/**
 * Eleven boards a player might actually build, written as spending plans.
 *
 * The question this project keeps asking is not "is the game winnable" but
 * "does more than one build win", and that cannot be answered by a single
 * board. Each entry here is one *shape* the tower set offers -- volume of
 * small hits, few big ones, splash at the corners, holding without killing,
 * a rate buff feeding two hot guns, and the ordinary mixture a new player
 * makes.
 *
 * A build is an *ordered* plan, not a finished board: the campaign harness
 * walks it front to back and buys the next entry when the purse allows, so
 * the order is the player's decision about what to own first. Repeating a
 * cell with a bigger suffix is how a plan says "come back and upgrade this".
 *
 * They are stored as loadout strings rather than as objects because the rule
 * in `loadout.ts` cuts both ways: if a build cannot be typed at the command
 * line, it cannot be reproduced by hand, and a measurement nobody can
 * reproduce is a rumour.
 *
 * ## What these boards learned from a real one
 *
 * Every board in this file used to be generated by spreading towers evenly
 * along the street and then improving whichever one was least improved. All
 * six lost, at every seed, while the game was being finished comfortably by
 * hand -- so the boards had stopped representing anybody, and the harness was
 * measuring its own generator rather than the game. A board played by hand and
 * recorded (`corner`, below) clears every seed with fourteen lives to spare.
 *
 * Two things separated it from the generated ones, and both are now the rule
 * here rather than the exception:
 *
 * **Concentrate.** Spreading by lane distance gives each tower one stretch of
 * road and no two towers the same crowd. The played board packed everything
 * into one knot beside the first hairpin -- thirteen towers inside a 240px box
 * that covers lane distances 160-400 *and* 840-960, because the street doubles
 * back through it. One Clara hurried six guns; one Barbara caught what all of
 * them were shooting at.
 *
 * **Finish a tower before starting the next.** Alternating upgrades across
 * every tower on the board is what a plan does when it has no opinion, and it
 * buys eight mediocre towers instead of four good ones.
 *
 * Coverage alone is not the trick, incidentally, and it was measured: putting
 * the old spread-out builds on the highest-coverage cells in the board, but
 * still scattered, still lost. The concentration is what pays.
 */

/** One tower in a build, and the capstone it ends on. */
interface Slot {
  def: TowerId;
  /**
   * The capstone this tower ends on, or none.
   *
   * On the slot rather than in a second list beside it. These used to be
   * paired by index and drifted: `control` asked a Knitting Norah for
   * Barbara's Big Batch and a Protest Pete for Walter's Stone Wall, eight
   * entries in all, and nothing caught it because the build was too poor to
   * ever reach them. A capstone that cannot be written apart from its tower
   * cannot come adrift from it. The `s` helper below types it per tower, so
   * the pairing is now checked where the build is written rather than only
   * when `render` runs.
   */
  capstone?: CapstoneId;
}

interface BuildSpec {
  blurb: string;
  /**
   * Where along the street this board knots itself, as a lane distance.
   *
   * Builds anchor in different places so they remain different boards; what
   * distinguishes them beyond that is what they are made of.
   */
  anchor: number;
  slots: Slot[];
}

/** How wide a knot may be. Wide enough to matter, tight enough for a Clara. */
const KNOT = 150;

/**
 * Resolve a build's slots to real cells, then write it in loadout grammar.
 *
 * Ordinary towers are clustered around the anchor, best-seeing cell first.
 * A blockade cannot be: Walter stands *in* the road, so his cell is chosen the
 * only way it can be, by lane distance.
 */
function render(spec: BuildSpec): string {
  const taken: { col: number; row: number }[] = [];
  const cells = spec.slots.map((s) => {
    if (s.capstone && !UPGRADES[s.def].capstones.some((c) => c.id === s.capstone)) {
      throw new Error(
        `build slot ${s.def} asks for capstone "${s.capstone}", which belongs to ` +
          `another tower -- ${s.def} has ${UPGRADES[s.def].capstones.map((c) => c.id).join(' and ')}`,
      );
    }
    const cell =
      s.def === 'walter'
        ? nearestCell(spec.anchor, 'blocker', taken)
        : clusterCells(spec.anchor, 1, TOWERS_RANGE[s.def], KNOT, taken)[0]!;
    taken.push(cell);
    return cell;
  });

  // Put one down, then improve whichever standing tower is furthest behind,
  // and once the board is full keep improving. Capstones last, because they
  // are the most expensive thing a plan can want and the board has to exist
  // first.
  //
  // Taking each tower all the way before placing the next was tried and is
  // worse, which was worth learning: it spends 285 coins finishing one Norah
  // while the street is still being walked by everything else, and `control`
  // died on round three of it. Concentration pays on the ground; it does not
  // pay in the order money is spent.
  const out: string[] = [];
  const tiers = spec.slots.map(() => ({ a: 0, b: 0 }));
  const placed: number[] = [];
  const at = (i: number): string => `${spec.slots[i]!.def}@${cells[i]!.col},${cells[i]!.row}`;
  const bits = (i: number): string =>
    (tiers[i]!.a ? `a${tiers[i]!.a}` : '') + (tiers[i]!.b ? `b${tiers[i]!.b}` : '');

  const improve = (): boolean => {
    const order = [...placed].sort(
      (x, y) => tiers[x]!.a + tiers[x]!.b - (tiers[y]!.a + tiers[y]!.b) || x - y,
    );
    for (const i of order) {
      const t = tiers[i]!;
      if (t.a <= t.b && t.a < 2) t.a++;
      else if (t.b < 2) t.b++;
      else continue;
      out.push(`${at(i)}+${bits(i)}`);
      return true;
    }
    return false;
  };

  spec.slots.forEach((_, i) => {
    out.push(at(i));
    placed.push(i);
    improve();
  });
  while (improve());
  spec.slots.forEach((s, i) => {
    if (s.capstone) out.push(`${at(i)}+a2b2:${s.capstone}`);
  });
  return out.join(' ');
}

/**
 * The reach each tower is placed for.
 *
 * A cell is picked for how much road *this* tower could see from it, so a Bill
 * is placed where his 225px reach pays and a Norah where her 95 does. Read
 * from the base stats rather than the bought ones: a plan chooses a cell
 * before it can afford the upgrades.
 */
const TOWERS_RANGE: Record<TowerId, number> = {
  norah: 95,
  barbara: 105,
  pete: 88,
  bill: 225,
  walter: 0,
  clara: 90,
  harold: 75,
  betty: 155,
};

const s = <T extends TowerId>(def: T, capstone?: CapstoneIds[T]): Slot => ({ def, capstone });

const SPECS: Record<string, BuildSpec> = {
  /** Knitters, and as little else as the shape allows. Volume of small hits. */
  swarm: {
    blurb: 'a knot of knitters, volume over size',
    anchor: 900,
    slots: [
      s('norah', 'longYarn'),
      s('norah', 'longYarn'),
      s('norah', 'tripleKnit'),
      s('norah', 'longYarn'),
      s('norah', 'tripleKnit'),
      s('norah', 'longYarn'),
      s('norah', 'tripleKnit'),
      s('norah', 'longYarn'),
      s('norah', 'tripleKnit'),
      s('norah', 'longYarn'),
      s('norah', 'tripleKnit'),
      s('norah', 'longYarn'),
    ],
  },

  /**
   * Hoses at the hairpin, where sending someone backwards costs them the most.
   *
   * A slip is worth exactly as much street as sits behind the hose, so the
   * knot where the road doubles back is the place it pays twice: a troublemaker
   * pushed back there walks the same stretch again past the same guns. The two
   * Norahs and the Bill are not decoration -- a board of nothing but Harolds
   * pushes people around without finishing any of them, which is the same
   * failure a board of nothing but Petes had.
   */
  slip: {
    blurb: 'hoses at the hairpin, walking them back over ground they have covered',
    anchor: 900,
    slots: [
      s('harold', 'soapyWater'),
      s('harold', 'fullMains'),
      s('norah', 'longYarn'),
      s('harold', 'soapyWater'),
      s('clara', 'doubleEspresso'),
      s('harold', 'fullMains'),
      s('norah', 'longYarn'),
      s('harold', 'soapyWater'),
      s('bill', 'deadeye'),
      s('harold', 'fullMains'),
    ],
  },

  /**
   * Bowling balls down a straight, with a wall to line the targets up.
   *
   * Betty is paid for a queue the way Barbara is paid for a clump, and a
   * blockade is the cheapest way to make a queue happen on purpose: everything
   * that stops at Walter is standing in single file behind him by the time the
   * ball arrives.
   */
  bowling: {
    blurb: 'bowling balls down a straight, with a wall to line them up',
    anchor: 1180,
    slots: [
      s('betty', 'theWholeLot'),
      s('betty', 'solidBall'),
      s('walter', 'stoneWall'),
      s('betty', 'theWholeLot'),
      s('clara', 'doubleEspresso'),
      s('betty', 'solidBall'),
      s('betty', 'theWholeLot'),
      s('norah', 'longYarn'),
      s('betty', 'solidBall'),
      s('betty', 'theWholeLot'),
      s('barbara', 'bigBatch'),
      s('betty', 'solidBall'),
    ],
  },

  /** Binoculars, where their reach covers the road going out and coming back. */
  sniper: {
    blurb: 'binoculars stacked where the street doubles back',
    anchor: 1180,
    slots: [
      s('bill', 'piercingShot'),
      s('bill', 'deadeye'),
      s('bill', 'piercingShot'),
      s('clara', 'doubleEspresso'),
      s('bill', 'deadeye'),
      s('bill', 'piercingShot'),
      s('norah', 'longYarn'),
      s('bill', 'deadeye'),
      s('bill', 'piercingShot'),
    ],
  },

  /** Cinnamon rolls where a crowd bunches up, and something to thin it. */
  area: {
    blurb: 'cinnamon rolls over a bend, where the crowd bunches',
    anchor: 620,
    slots: [
      s('norah', 'longYarn'),
      s('barbara', 'bigBatch'),
      s('barbara', 'freshBatch'),
      s('barbara', 'bigBatch'),
      s('barbara', 'freshBatch'),
      s('clara', 'doubleEspresso'),
      s('barbara', 'bigBatch'),
      s('barbara', 'freshBatch'),
      s('norah', 'longYarn'),
      s('barbara', 'bigBatch'),
    ],
  },

  /** Stun and a blockade, holding the road while a thin gun line works. */
  control: {
    // Three Protest Petes and no Binocular Bill was not a control board, it was
    // a board that could not finish anything: Pete deals 5 and buys time, so a
    // plan full of him stalls the street and then starves. One Pete, a wall,
    // and a gun line for the holding to be worth something.
    //
    // The old version also leaned on a bug rather than on Walter -- everything
    // queued behind a fallen blockade used to freeze for the whole six seconds
    // of Second Wind, taking and dealing no damage. With that fixed, this shape
    // still clears and the old one collapses, which says the build was living
    // on the freeze rather than on the blockade.
    blurb: 'a garden wall and a megaphone, holding while the gun line works',
    anchor: 1180,
    slots: [
      s('norah', 'longYarn'),
      s('barbara', 'bigBatch'),
      s('walter', 'stoneWall'),
      s('norah', 'longYarn'),
      s('pete', 'bullhorn'),
      s('clara', 'doubleEspresso'),
      s('barbara', 'bigBatch'),
      s('bill', 'piercingShot'),
      s('norah', 'longYarn'),
      s('barbara', 'bigBatch'),
    ],
  },

  /** Coffee stacked on a small number of guns run very hot. */
  support: {
    blurb: 'three coffees, everything nearby firing far too fast',
    anchor: 1500,
    slots: [
      s('norah', 'longYarn'),
      s('clara', 'doubleEspresso'),
      s('bill', 'deadeye'),
      s('clara', 'secondRound'),
      s('norah', 'longYarn'),
      s('bill', 'piercingShot'),
      s('clara', 'doubleEspresso'),
      s('norah', 'longYarn'),
      s('bill', 'deadeye'),
      s('norah', 'longYarn'),
      s('bill', 'piercingShot'),
      s('clara', 'secondRound'),
      s('bill', 'deadeye'),
      s('norah', 'longYarn'),
    ],
  },

  /** One of most things: the board a first-time player ends up with. */
  mixed: {
    blurb: 'one of most things, the obvious first board',
    anchor: 340,
    slots: [
      s('norah', 'longYarn'),
      s('bill', 'piercingShot'),
      s('clara', 'secondRound'),
      s('barbara', 'bigBatch'),
      s('bill', 'deadeye'),
      s('norah', 'longYarn'),
      s('pete', 'bullhorn'),
      s('bill', 'piercingShot'),
      s('barbara', 'freshBatch'),
      s('norah', 'longYarn'),
      s('bill', 'deadeye'),
      s('clara', 'doubleEspresso'),
      s('barbara', 'bigBatch'),
    ],
  },
};

/**
 * The boards played by hand and recorded, kept exactly as they were played.
 *
 * Written out rather than generated, because that is the point of them: they
 * are the only entries here that are evidence rather than a proposal, and
 * rewriting one into the vocabulary above would quietly turn it back into a
 * proposal. Each was captured with the `L` key while playing at
 * localhost:5173 -- see CLAUDE.md.
 *
 * Keep every one of them verbatim. If a change to the game stops a played
 * board clearing, that is a finding worth having, and it is only worth having
 * while the board is still the one somebody actually played.
 *
 * These outrank the generated boards rather than standing beside them. The
 * difficulty curve is tuned until *these* feel it; `SPECS` above is the net
 * that catches a change which happens to suit one board and ruins the rest.
 * A generated plan going red is a question about the plan. A played board
 * going red is a question about the game.
 */
const CORNER =
  'norah@3,4 norah@7,6 norah@7,6+b1 norah@7,6+a1b1 norah@7,6+a1b2 norah@3,4+a1 ' +
  'norah@7,6+a2b2 norah@3,4+a1b1 norah@3,4+a2b1 bill@9,5 bill@9,5+b1 norah@3,4+a2b2 ' +
  'norah@7,6+a2b2:longYarn norah@3,4+a2b2:longYarn clara@6,5 clara@6,5+b1 clara@6,5+b2 ' +
  'bill@9,5+b2 bill@9,5+a1b2 barbara@4,5 barbara@4,5+a1 barbara@4,5+a2 barbara@4,5+a2b1 ' +
  'barbara@4,5+a2b2 barbara@4,5+a2b2:bigBatch clara@6,5+a1b2 clara@6,5+a2b2 ' +
  'clara@6,5+a2b2:secondRound bill@9,5+a2b2 bill@9,5+a2b2:piercingShot bill@9,6 ' +
  'bill@9,6+a1 bill@9,6+a2 bill@9,6+a2b1 bill@9,6+a2b2 bill@9,6+a2b2:piercingShot ' +
  'norah@8,5 norah@8,5+b1 norah@8,5+b2 norah@8,5+a1b2 norah@8,5+a2b2 ' +
  'norah@8,5+a2b2:longYarn pete@4,4 pete@4,4+a1 pete@4,4+a2 pete@4,4+a2b1 pete@4,4+a2b2 ' +
  'bill@9,4 pete@4,4+a2b2:bullhorn bill@9,4+a1 bill@9,4+a2 bill@9,4+a2b1 bill@9,4+a2b2 ' +
  'bill@9,4+a2b2:piercingShot barbara@7,7 barbara@7,7+a1 barbara@7,7+a2 barbara@7,7+a2b1 ' +
  'barbara@7,7+a2b2 barbara@7,7+a2b2:bigBatch bill@9,3 bill@8,4 bill@7,5';

export interface Build {
  name: string;
  blurb: string;
  /** The plan, in the grammar `parseLoadout` reads. */
  loadout: string;
  /**
   * Whether a person played this board, or `render` generated it.
   *
   * The distinction used to live only in a comment, which meant nothing
   * downstream could act on it and the balance sweep weighed a recording and a
   * proposal the same. `tests/balance.test.ts` now reads this.
   */
  played: boolean;
}

/**
 * A second board played by hand, deliberately without a Knitting Norah.
 *
 * Where `corner` is a knot of cheap fast hits with one Bill in it, this is the
 * opposite reading of the same street: seven Binocular Bills taken all the way
 * to Piercing Shot, one Clara to hurry them, and a Barbara and a Pete for the
 * crowd. It matters because it shares almost nothing with `corner` -- if a
 * change to the game suits one of them and not the other, that shows up here
 * and nowhere in the generated boards.
 */
const BINOCULARS =
  'bill@10,6 bill@10,6+b1 bill@10,6+b2 clara@8,6 clara@8,6+a1 bill@10,6+a1b2 pete@6,5 ' +
  'bill@10,5 bill@10,5+b1 bill@10,5+a1b1 bill@10,5+a1b2 bill@10,6+a2b2 clara@8,6+a2 ' +
  'clara@8,6+a2b1 clara@8,6+a2b2 clara@8,6+a2b2:secondRound bill@10,8 bill@10,8+b1 ' +
  'bill@10,8+b2 bill@10,8+a1b2 bill@10,8+a2b2 bill@10,6+a2b2:piercingShot ' +
  'bill@10,8+a2b2:piercingShot barbara@7,7 barbara@7,7+a1 barbara@7,7+a2 barbara@7,7+a2b1 ' +
  'barbara@7,7+a2b2 barbara@7,7+a2b2:bigBatch bill@7,6 bill@7,6+b1 bill@7,6+b2 ' +
  'bill@7,6+a1b2 bill@7,6+a2b2 bill@7,6+a2b2:piercingShot bill@9,5 bill@10,5+a2b2 ' +
  'bill@10,5+a2b2:piercingShot bill@9,5+a1 bill@9,5+a1b1 bill@9,5+a1b2 bill@9,5+a2b2 ' +
  'bill@9,5+a2b2:piercingShot bill@6,3 bill@6,3+a1 bill@6,3+a2 bill@6,3+a2b1 bill@6,3+a2b2 ' +
  'bill@6,3+a2b2:piercingShot bill@8,5 bill@8,5+b1 bill@8,5+b2 bill@8,5+a1b2 bill@8,5+a2b2 ' +
  'bill@8,5+a2b2:piercingShot';

/**
 * A third board played by hand: garden walls, cinnamon rolls and knitters.
 *
 * The only played board that puts Walter in the road at all -- three of them,
 * side by side at the bottom of the street -- and the only one built around
 * Barbara's splash rather than around a gun. Six Norahs and two Claras behind
 * the wall do the killing while the blockades hold the crowd in the splash.
 *
 * It completes the set: `corner` is cheap fast hits in a knot, `binoculars` is
 * a few big ones down a straight, and this is holding ground and letting an
 * area do the work. Three different answers to the same street.
 */
const WALL =
  'barbara@7,7 barbara@3,5 barbara@9,7 barbara@7,7+a1 barbara@7,7+a2 barbara@3,5+a1 ' +
  'clara@7,6 clara@7,6+a1 clara@7,6+a1b1 norah@8,6 norah@8,6+b1 norah@8,6+b2 ' +
  'barbara@7,7+a2b1 barbara@7,7+a2b2 norah@8,6+a1b2 norah@8,6+a2b2 ' +
  'norah@8,6+a2b2:longYarn barbara@7,7+a2b2:bigBatch clara@7,6+a2b1 clara@7,6+a2b2 ' +
  'clara@7,6+a2b2:secondRound walter@9,9 walter@8,9 walter@7,9 walter@7,9+b1 ' +
  'walter@7,9+a1b1 walter@7,9+a2b1 walter@7,9+a2b2 norah@6,6 norah@6,6+a1 ' +
  'norah@6,6+a1b1 norah@6,6+a2b1 norah@6,6+a2b2 norah@6,6+a2b2:tripleKnit norah@6,5 ' +
  'norah@6,5+a1 norah@6,5+a2 norah@6,5+a2b1 norah@6,5+a2b2 norah@6,5+a2b2:tripleKnit ' +
  'norah@7,5 norah@7,5+a1 norah@7,5+a1b1 norah@7,5+a2b1 norah@7,5+a2b2 ' +
  'norah@7,5+a2b2:tripleKnit clara@8,7 clara@8,7+a1 clara@8,7+a2 clara@8,7+a2b1 ' +
  'clara@8,7+a2b2 clara@8,7+a2b2:doubleEspresso barbara@9,7+a1 bill@10,7 bill@10,7+b1 ' +
  'bill@10,7+b2 bill@10,7+a1b2 bill@10,7+a2b2 bill@10,7+a2b2:deadeye norah@6,7 ' +
  'norah@6,7+a1 norah@6,7+a2 norah@6,7+a2b1 norah@6,7+a2b2 norah@6,7+a2b2:tripleKnit ' +
  'norah@9,6 norah@9,6+a1 norah@9,6+a2 norah@9,6+a2b1 norah@9,6+a2b2 ' +
  'norah@9,6+a2b2:longYarn';

/** The recorded boards, in the order they were played. */
const PLAYED_BUILDS: Omit<Build, 'played'>[] = [
  { name: 'corner', blurb: 'played by hand at the first hairpin, and won', loadout: CORNER },
  {
    name: 'binoculars',
    blurb: 'played by hand with no knitters, seven binoculars down the street, and won',
    loadout: BINOCULARS,
  },
  {
    name: 'wall',
    blurb: 'played by hand behind three garden walls, cinnamon rolls doing the work, and won',
    loadout: WALL,
  },
];

export const BUILDS: Build[] = [
  ...Object.entries(SPECS).map(([name, spec]) => ({
    name,
    blurb: spec.blurb,
    loadout: render(spec),
    played: false,
  })),
  ...PLAYED_BUILDS.map((b) => ({ ...b, played: true })),
];

/**
 * The boards a person actually played.
 *
 * What the difficulty curve is aimed at. Kept as its own export so a test can
 * say which standard it is applying without re-deriving the distinction.
 */
export const REFERENCE_BUILDS: Build[] = BUILDS.filter((b) => b.played);

export const BUILD_NAMES: string[] = BUILDS.map((b) => b.name);

export function buildNamed(name: string): Build {
  const found = BUILDS.find((b) => b.name === name);
  if (!found) throw new Error(`no build "${name}" -- known: ${BUILD_NAMES.join(', ')}`);
  return found;
}
